---
title: "bootstrapping"
author: "Yuchen Hua"
date: "2022-11-26"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

```{r}
sim_df_const %>%
  ggplot(aes(x = x, y = y))+
  geom_point() +
  geom_smooth(method = "lm")

sim_df_nonconst %>%
  ggplot(aes(x = x, y = y))+
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
lm( y ~x, data = sim_df_const) %>% broom::tidy()
lm( y ~x, data = sim_df_nonconst) %>% broom::tidy()
```

## Draw one bootstrap sample

```{r}
boot_sample = function(df){
  sample_frac(df, replace = TRUE) %>%
    arrange(x)
}
```
check if it works
```{r}
boot_sample(sim_df_nonconst) %>%
  ggplot(aes(x = x, y = y))+
  geom_point(alpha = .3) +
  geom_smooth(method = "lm") +
  ylim(-5, 16)
```

```{r}
boot_sample(sim_df_nonconst) %>%
  lm(y~x, data=.) %>%
  broom::tidy()
```





